### PR TITLE
Refactor/104 flyby point singularity fix

### LINKED ISSUE #104: flybyPoint singularity fix
**Describe your use case**
Aims to improve flybyPoint module to make it robust to collinear relative position and velocity vectors w.r.t. the asteroid/flyby object.

**Additional context**
A singularity occurs in the situation described above. This fix aims at providing a smooth solution for the reference frame when the system is near the singular configuration.

### PR DESCRIPTION
**Pull request by rcalaon**
* **Tickets addressed:** bsk-104
* **Review:** By commit  
* **Merge strategy:** Merge (no squash)  

## Description
A routine is added to check whether relative position and velocity vector are parallel within tolerance. When this is the case, the output frame defaults to a compliant solution, and angular rates and accelerations default to zero.

## Verification
Unit test is provided.

## Documentation
Documentation is updated to reflect the changes.

## Future work
No future work is foreseen at the moment.

### CODE REVIEW

File: src/fswAlgorithms/attGuidance/flybyPoint/flybyPoint.cpp [hunk 1]
```diff
@@ -77,11 +77,25 @@ void FlybyPoint::UpdateState(uint64_t CurrentSimNanos)
...
+            this->singularityFlag = 1;
+        }
+        else if (dot + 1 < this->epsilon) {
+            v3Perpendicular(ur_N, uh_N);
+            this->singularityFlag = -1;
+        }
+        else {
+            v3Cross(ur_N, uv_N, uh_N);
+            this->singularityFlag = 0;
+        }
```
Comment (thibaudteil) [inline src/fswAlgorithms/attGuidance/flybyPoint/flybyPoint.cpp]: I would not create the temporary dot variable and just check for 1-dot being less/greater than epsilon inside the ifs in line 114 to 122. That would remove the singularityFlag and would be a bit more legible

File: src/fswAlgorithms/attGuidance/flybyPoint/flybyPoint.cpp [hunk 2]
```diff
@@ -97,15 +111,29 @@ void FlybyPoint::UpdateState(uint64_t CurrentSimNanos)
...
 
     /*! compute rotation angle of reference frame from last read time */
-    double theta = atan(tan(this->gamma0) + this->f0 / cos(this->gamma0) * dt) -this->gamma0;
+    double theta;
+    if (this->singularityFlag == 0) {
+        theta = atan(tan(this->gamma0) + this->f0 / cos(this->gamma0) * dt) - this->gamma0;
+    }
+    else {
+        theta = 0;
+    }
```
Comment (thibaudteil) [inline src/fswAlgorithms/attGuidance/flybyPoint/flybyPoint.cpp]: Maybe I'm wrong, but I believe this could be done inside the previous ifs as well to avoid several similar ifs

**Review by thibaudteil — COMMENTED** [review]
Small changes, I'll test it in sim as well

File: src/fswAlgorithms/attGuidance/flybyPoint/flybyPoint.cpp (hunk 2 above)
Comment (rcalaon) [reply src/fswAlgorithms/attGuidance/flybyPoint/flybyPoint.cpp]: I don't think so. This theta in particular is a function of dt, and therefore needs to be calculated outside of the if statement that starts on line 71. Otherwise it would not get updated at every call, but only at every filter read. Because I need a variable (singularityFlag) to pass that information from inside that big if statement, I think it makes more sense to leave it.

File: src/fswAlgorithms/attGuidance/flybyPoint/flybyPoint.cpp (hunk 1 above)
Comment (rcalaon) [reply src/fswAlgorithms/attGuidance/flybyPoint/flybyPoint.cpp]: I've removed the dot variable and combined this if statement into the previous one. I think I still need the singularityFlag, see the reply to your other comment.

File: src/fswAlgorithms/attGuidance/flybyPoint/flybyPoint.cpp (hunk 2 above)
Comment (thibaudteil) [reply src/fswAlgorithms/attGuidance/flybyPoint/flybyPoint.cpp]: Ok
