### PR TITLE
Fix <float>bmatrix test accuracy check

### LINKED ISSUE #528: <float>BMatMRP test occasionally fails its accuracy check
**Describe the bug**
<float>BMatMRP test occasionally fails its accuracy check as the accuracy threshold is too tight for the size of the domain to the function.

**To reproduce**
1. Run the BMatMRP test a handful of times.

**Expected behavior**
The test should verify correctness and pass for the full domain of inputs.

**Screenshots**
NA

**Desktop (please complete the following information):**
- OS: Macos 
- Version 15.7
- Python version 3.11

**Additional context**
None

### PR DESCRIPTION
**Pull request by patkenneally**
* **Tickets addressed:**  #528
* **Review:** By commit
* **Merge strategy:** Merge (no squash)

## Description
This PR adjusts the tests in `test_rigidBodyKinematics.hpp` to use a relative tolerance that is computed based upon the scale of input or expected values (whichever is appropriate). This tightens the accuracy constraint appropriate for either type of floating point number `float` or `double`.

## Verification
The test suite runs successfully.

## Documentation
None

## Future work
None

### CODE REVIEW

**Review by JulianHammerl — APPROVED** [review]

File: src/architecture/utilities/tests/test_rigidBodyKinematics.cpp [hunk 1]
```diff
@@ -5,19 +5,77 @@
...
+}
+
+template <typename DerivedA, typename DerivedB>
+typename DerivedA::Scalar relativeErrorNorm(const Eigen::MatrixBase<DerivedA>& actual,
+                                            const Eigen::MatrixBase<DerivedB>& expected) {
+    using Scalar = typename DerivedA::Scalar;
+    static_assert(std::is_same_v<Scalar, typename DerivedB::Scalar>, "Scalar mismatch in relativeErrorNorm");
+    const Scalar eps = std::numeric_limits<Scalar>::epsilon();
+    const Scalar scale = std::max(expected.norm(), static_cast<Scalar>(1));
+    return (actual - expected).norm() / (scale + eps);
```
Comment (thibaudteil) [inline src/architecture/utilities/tests/test_rigidBodyKinematics.cpp:78]: I'm curious to get a better understanding of this, but that shouldn't hold up this ticket

**Review by thibaudteil — APPROVED** [review]

File: src/architecture/utilities/tests/test_rigidBodyKinematics.cpp (hunk 1 above)
Comment (patkenneally) [reply src/architecture/utilities/tests/test_rigidBodyKinematics.cpp:78]: I'll write up an explainer. And we can chat.
